Repository AY2021S1-CS2103T-T17-1/tp, pull requests merged in 2020-11, with the labels that each got.

#179 Fix RecommendSU filtering module list and affecting the next command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#176 Add Semester parameter for list command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RecommendSuCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/semester/SemesterManager.java
  src/main/java/seedu/address/model/util/ModuleListFilter.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/RecommendSuCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: type.Bug

#174 Change range of valid MCs from 1 to 16
  src/main/java/seedu/address/model/module/ModularCredit.java
Labels: type.Bug

#193 Change prefix to fix wrong message shown
  docs/team/zhaolingshan.md
  src/main/java/seedu/address/logic/commands/ProgressCommand.java
  src/main/java/seedu/address/logic/commands/SuCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/module/GoalTarget.java
Labels: priority.High, type.Bug

#198 Disallow additional user input after 'recommendSU'
  src/main/java/seedu/address/logic/commands/RecommendSuCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/RecommendSuCommandParser.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RecommendSuCommandParserTest.java
Labels: priority.High, type.Bug

#214 Update PPP for augustinekau.
  docs/team/augustinekau.md
Labels: documentation

#218 Accept lower case input for semester
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
Labels: priority.High, type.Task

#220 Branch edit list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.High, type.Task

#228 Update HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Task

#226 First version of PPP
  docs/team/zhaolingshan.md
Labels: priority.High, type.Task

#229 Add PPP
  docs/team/xyzhangg.md
Labels: documentation, priority.High, type.Task

#232 Edit tests and add constant variables in CommandTestUtil
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExitCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ProgressCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RecommendSuCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StartCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
Labels: priority.High, type.Task

#246 Branch ug minor edits
  docs/UserGuide.md
  docs/images/UG SS/1. Logo.png
  docs/images/UG SS/2.14 Get Help 2.png
Labels: documentation

#250 Fix sort modules by semester
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/ModuleComparator.java
Labels: priority.Medium, type.Task

#251 Branch dg
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/RecommendSuActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/RecommendSuActivityDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#256 Debug clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/parser/ClearCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
Labels: priority.High, type.Bug

#257 Update dg logic sequence diagram and progress activity diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ProgressActivityDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/ProgressActivityDiagram.png
Labels: documentation

#274 Add Start Semester and diagrams in DG
  docs/DeveloperGuide.md
  docs/diagrams/StartSemesterActivityDiagram.puml
  docs/diagrams/StartSemesterSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StartSemesterSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/commands/SuCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/module/ModuleName.java
Labels: documentation

#278 Edit Start Semester activity diagram
  docs/DeveloperGuide.md
  docs/images/StartSemesterActivityDiagram.png
Labels: documentation

#290 Debug and edit tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/SuCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/SuCommandParser.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SuCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SuCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleModuleNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/module/ModuleNameTest.java
Labels: priority.High, type.Bug

#297 Update PPP
  docs/team/xyzhangg.md
Labels: documentation

#300 Update PPP
  docs/team/pongzers.md
  docs/team/zhaolingshan.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation
