Repository AY2021S1-CS2103T-T17-1/tp, pull requests merged in 2020-10, with the labels that each got.

#43 Remove phone class
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#44 Remove email class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#48 Update MainWindow FXML to represent modules
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListPanel.fxml
Labels: type.Task

#49 Update ListCommand
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
Labels: type.Task

#75 Add checking of MCs functionality
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/ModularCredit.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/ModuleInfoRetriever.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Task

#79 Add start command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StartCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/semester/Semester.java
  src/main/java/seedu/address/model/semester/SemesterManager.java
  src/main/java/seedu/address/model/util/ModuleListFilter.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/AutoCompleteTextField.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/testutil/ModuleBuilder.java
Labels: priority.High, type.Task

#82 Add DoneCommand
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
Labels: priority.High, type.Task

#84 Add progress command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ProgressCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ProgressCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/McCalculator.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ProgressCommandTest.java
Labels: priority.High, type.Task

#87 Add functionality to sort module list by semester
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/semester/Semester.java
  src/main/java/seedu/address/model/util/ModuleComparator.java
  src/main/java/seedu/address/model/util/ModuleListSorter.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Task

#105 Branch update ug
  docs/UserGuide.md
  docs/images/UG SS/2.6 Set Goals 1.png
  docs/images/UG SS/2.6 Set Goals 2.png
  docs/images/UG SS/2.7 Recommend SU 1.png
  docs/images/UG SS/2.7 Recommend SU 2.png
  docs/images/UG SS/2.7 Recommend SU 3.png
Labels: documentation

#106 Branch update ug two
  docs/UserGuide.md
  docs/images/UG SS/2.10 Exit Semester 1.png
  docs/images/UG SS/2.10 Exit Semester 2.png
  docs/images/UG SS/2.11 Progress Report 1.png
  docs/images/UG SS/2.11 Progress Report 2.png
  docs/images/UG SS/2.12 Get Help 1.png
  docs/images/UG SS/2.12 Get Help 2.png
  docs/images/UG SS/2.13 Exit Application 1.png
  docs/images/UG SS/2.2 Edit Semester 1.png
  docs/images/UG SS/2.2 Edit Semester 2.png
  docs/images/UG SS/2.3 Add Module 1.png
  docs/images/UG SS/2.3 Add Module 2.png
  docs/images/UG SS/2.3 Add Module 3.png
  docs/images/UG SS/2.4 Update Module 1.png
  docs/images/UG SS/2.4 Update Module 2.png
  docs/images/UG SS/2.4 Update Module 3.png
  docs/images/UG SS/2.5 List all Modules 1.png
  docs/images/UG SS/2.5 List all Modules 2.png
  docs/images/UG SS/2.5 List all Modules 3.png
  docs/images/UG SS/2.8 SU Module 1.png
  docs/images/UG SS/2.9 Delete Module 1.png
  docs/images/UG SS/2.9 Delete Module 2.png
  docs/images/UG SS/2.9 Delete Module 3.png
  docs/images/UG SS/2.9 Delete Module 4.png
Labels: documentation

#108 Ui/RecommendSU testing and UG update
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RecommendSuCommand.java
  src/main/java/seedu/address/ui/AutoCompleteTextField.java
  src/main/java/seedu/address/ui/CapBox.java
  src/main/java/seedu/address/ui/DragResizer.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/RecommendSuCommandTest.java
  src/test/java/seedu/address/ui/CapBoxTest.java
Labels: documentation

#109 UG update
  docs/UserGuide.md
Labels: documentation

#107 Branch update ug features 2.8, 2.9
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation

#110 Update help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium, type.Task

#116 Branch debug DeleteCommand and EditCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, type.Bug

#117 Branch debug DoneCommand
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/RecommendSuCommand.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/RecommendSuCommandTest.java
Labels: priority.High, type.Bug

#121 Branch debug ExitCommand
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/test/java/seedu/address/logic/parser/ExitCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
Labels: priority.High, severity.Medium, type.Bug

#123 Branch debug HelpCommand
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
  src/test/java/seedu/address/logic/parser/HelpCommandParserTest.java
Labels: priority.High, severity.Medium, type.Bug

#124 Branch debug ListCommand
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
Labels: priority.High, severity.Medium, type.Bug

#119 Refactor edit to update
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/StartCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateModNameDescriptorTest.java
  src/test/java/seedu/address/logic/parser/GradeBookParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateCommandParserTest.java
  src/test/java/seedu/address/model/GradeBookTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/testutil/EditModNameDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/UpdateModNameDescriptorBuilder.java
Labels: priority.High, severity.Medium

#129 Update ProgressCommandTest and ProgressCommandParserTest
  src/main/java/seedu/address/logic/commands/ProgressCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/ProgressCommandTest.java
  src/test/java/seedu/address/logic/parser/ProgressCommandParserTest.java
Labels: priority.High, type.Task

#131 Update UG
  docs/UserGuide.md
Labels: documentation

#132 Update ModuleCard to display semester
  src/main/java/seedu/address/ui/ModuleCard.java
Labels: priority.Medium, type.Task

#128 Add SU command
  src/main/java/seedu/address/logic/commands/SuCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SuCommandParser.java
  src/main/java/seedu/address/model/module/Cap.java
  src/main/java/seedu/address/model/util/CapCalculator.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Task
